spring:
  application:
    name: hub-service

  data:
    redis:
      host: localhost
      port: 6379
      username: ${REDIS_NAME}
      password: ${REDIS_PASSWORD}

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRESQL_DB_NAME}
    username: ${POSTGRESQL_NAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: never #alwqys-> Run할때마다 data.sql 데이터 삽입 never-> data.sql 파일 신경 안씀 (처음 추가한 다음 never 바꿔주세요)


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    access-expiration: 3600000
    secret-key: ${JWT_SECRET_KEY}
server:
  port: 19101

kakao:
  api:
    key: bc810dfa4da1b613f598f9e3e098ecc4
jackson:
  date-format: "yyyy-MM-dd'T'HH:mm:ss"
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false