server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ai-messages/**
        - id: slack-service
          uri: lb://slack-service
          predicates:
            - Path=/api/v1/slack/**
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/api/v1/hubs/**, /api/v1/hubroutes/**
        - id: shipment-service
          uri: lb://shipment-service
          predicates:
            - Path=/api/v1/shipments/**, /api/v1/shipment-managers/**, /api/v1/shipment-routes/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/v1/companies/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
